name: PyInstaller
on:
  push:
    branches:
      - master

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./code
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          # - macos-latest # doesn't run for free
          - windows-latest
        version:
          - '3.10'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: ${{ matrix.version }}
          spec: 'code/main.py'
          requirements: 'code/requirements.txt'
          upload_exe_with_name: 'NonPlanarSlicingDeformation-py${{ matrix.version }}-${{ matrix.os }}'
          options: --onefile, --name "Non Planar Desformation", --windowed, 
