name: PyInstaller
on:
  push:
    branches:
      - master

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./code
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          # - macos-latest # doesn't run for free
          - windows-latest
        version:
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install linux deps
        if: contains(matrix.os, 'ubuntu')
        # Needed by pyside6
        run: |
          sudo apt install -y libxcb-* libxkbcommon-x11-0 freeglut3-dev
         
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install PyInstaller
     
      - name: Run PyInstaller
        run: |
          python3 -m PyInstaller --clean --noconfirm --dist ./dist --onefile --name "NonPlanarSlicingDeformation" --windowed main.py

      - name: Test executable linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          ./dist/NonPlanarSlicingDeformation --test

      - name: Test executable windows
        if: contains(matrix.os, 'windows')
        run: |
          dist\NonPlanarSlicingDeformation.exe --test

      - name: Upload artifact linux
        if: contains(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v4
        with:
          name: "NonPlanarSlicingDeformation-py${{ matrix.version }}-${{ matrix.os }}"
          path: ${{ github.workspace }}/code/dist/NonPlanarSlicingDeformation
          if-no-files-found: error

      - name: Upload artifact windows
        if: contains(matrix.os, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: "NonPlanarSlicingDeformation-py${{ matrix.version }}-${{ matrix.os }}"
          path: ${{ github.workspace }}\code\dist\NonPlanarSlicingDeformation.exe
          if-no-files-found: error

